<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Artificial Neural Network | Indirect Obesity Forecasting</title>
  <meta name="description" content="This is our team project for TO628. In this project, we are exploring innovative predictive analytics methods to assess and manage obesity in the context of potential government-imposed BMI usage restrictions. Utilizing the Proxy Health Evaluation System (PHES), our approach circumvents these potential limitations, providing health insurance companies and medical professionals with essential insights to develop proactive health programs and enhance patient outcomes." />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Artificial Neural Network | Indirect Obesity Forecasting" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="//Users/blakew/Desktop/UM_MBAn/TO628/to_628_hidden_image.jpg" />
  <meta property="og:description" content="This is our team project for TO628. In this project, we are exploring innovative predictive analytics methods to assess and manage obesity in the context of potential government-imposed BMI usage restrictions. Utilizing the Proxy Health Evaluation System (PHES), our approach circumvents these potential limitations, providing health insurance companies and medical professionals with essential insights to develop proactive health programs and enhance patient outcomes." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Artificial Neural Network | Indirect Obesity Forecasting" />
  
  <meta name="twitter:description" content="This is our team project for TO628. In this project, we are exploring innovative predictive analytics methods to assess and manage obesity in the context of potential government-imposed BMI usage restrictions. Utilizing the Proxy Health Evaluation System (PHES), our approach circumvents these potential limitations, providing health insurance companies and medical professionals with essential insights to develop proactive health programs and enhance patient outcomes." />
  <meta name="twitter:image" content="//Users/blakew/Desktop/UM_MBAn/TO628/to_628_hidden_image.jpg" />

<meta name="author" content="Aaron Zhao" />
<meta name="author" content="Arneet Singh" />
<meta name="author" content="Blake Waldman" />
<meta name="author" content="Grace Coleman" />
<meta name="author" content="Tyler James Phillips" />
<meta name="author" content="Yousuf Altameemi" />


<meta name="date" content="2024-04-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introduction-1.html"/>
<link rel="next" href="footnotes-and-citations.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="to_628_hidden_image.jpg" 
alt="TO 628 Group Project" 
title="TO 628 Group Project"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#dataset-overview"><i class="fa fa-check"></i>Dataset Overview</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#audience-and-impact"><i class="fa fa-check"></i>Audience and Impact</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#challenges-in-health-insurance"><i class="fa fa-check"></i>Challenges in Health Insurance</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#medical-professional-engagement"><i class="fa fa-check"></i>Medical Professional Engagement</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#research-questions"><i class="fa fa-check"></i>Research Questions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#adoption-and-implementation"><i class="fa fa-check"></i>Adoption and Implementation</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#strategic-impact"><i class="fa fa-check"></i>Strategic Impact</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="initial-analysis.html"><a href="initial-analysis.html"><i class="fa fa-check"></i><b>2</b> Initial Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="initial-analysis.html"><a href="initial-analysis.html#r-packages-and-setup"><i class="fa fa-check"></i>R Packages and Setup</a></li>
<li class="chapter" data-level="2.1" data-path="initial-analysis.html"><a href="initial-analysis.html#load-data"><i class="fa fa-check"></i><b>2.1</b> Load Data</a></li>
<li class="chapter" data-level="2.2" data-path="initial-analysis.html"><a href="initial-analysis.html#clean-data"><i class="fa fa-check"></i><b>2.2</b> Clean Data</a></li>
<li class="chapter" data-level="2.3" data-path="initial-analysis.html"><a href="initial-analysis.html#feature-engineering"><i class="fa fa-check"></i><b>2.3</b> Feature Engineering</a></li>
<li class="chapter" data-level="2.4" data-path="initial-analysis.html"><a href="initial-analysis.html#visualize-data"><i class="fa fa-check"></i><b>2.4</b> Visualize Data</a></li>
<li class="chapter" data-level="2.5" data-path="initial-analysis.html"><a href="initial-analysis.html#split-data"><i class="fa fa-check"></i><b>2.5</b> Split Data</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="initial-analysis.html"><a href="initial-analysis.html#split-train-test"><i class="fa fa-check"></i><b>2.5.1</b> Split Train Test</a></li>
<li class="chapter" data-level="2.5.2" data-path="initial-analysis.html"><a href="initial-analysis.html#split-lr"><i class="fa fa-check"></i><b>2.5.2</b> Split LR</a></li>
<li class="chapter" data-level="2.5.3" data-path="initial-analysis.html"><a href="initial-analysis.html#split-dt"><i class="fa fa-check"></i><b>2.5.3</b> Split DT</a></li>
<li class="chapter" data-level="2.5.4" data-path="initial-analysis.html"><a href="initial-analysis.html#split-svm"><i class="fa fa-check"></i><b>2.5.4</b> Split SVM</a></li>
<li class="chapter" data-level="2.5.5" data-path="initial-analysis.html"><a href="initial-analysis.html#split-rf"><i class="fa fa-check"></i><b>2.5.5</b> Split RF</a></li>
<li class="chapter" data-level="2.5.6" data-path="initial-analysis.html"><a href="initial-analysis.html#split-xgb"><i class="fa fa-check"></i><b>2.5.6</b> Split XGB</a></li>
<li class="chapter" data-level="2.5.7" data-path="initial-analysis.html"><a href="initial-analysis.html#split-ann"><i class="fa fa-check"></i><b>2.5.7</b> Split ANN</a></li>
<li class="chapter" data-level="2.5.8" data-path="initial-analysis.html"><a href="initial-analysis.html#split-knn"><i class="fa fa-check"></i><b>2.5.8</b> Split KNN</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introduction-1.html"><a href="introduction-1.html"><i class="fa fa-check"></i><b>3</b> Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-1.html"><a href="introduction-1.html#r-packages-and-setup-1"><i class="fa fa-check"></i>R Packages and Setup</a></li>
<li class="chapter" data-level="3.1" data-path="introduction-1.html"><a href="introduction-1.html#simple-lr"><i class="fa fa-check"></i><b>3.1</b> Simple LR</a></li>
<li class="chapter" data-level="3.2" data-path="introduction-1.html"><a href="introduction-1.html#complex-lr"><i class="fa fa-check"></i><b>3.2</b> Complex LR</a></li>
<li class="chapter" data-level="3.3" data-path="introduction-1.html"><a href="introduction-1.html#stepwise-lr"><i class="fa fa-check"></i><b>3.3</b> Stepwise LR</a></li>
<li class="chapter" data-level="3.4" data-path="introduction-1.html"><a href="introduction-1.html#simple-lr-1"><i class="fa fa-check"></i><b>3.4</b> Simple LR</a></li>
<li class="chapter" data-level="3.5" data-path="introduction-1.html"><a href="introduction-1.html#complex-lr-1"><i class="fa fa-check"></i><b>3.5</b> Complex LR</a></li>
<li class="chapter" data-level="3.6" data-path="introduction-1.html"><a href="introduction-1.html#stepwise-lr-1"><i class="fa fa-check"></i><b>3.6</b> Stepwise LR</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="artificial-neural-network.html"><a href="artificial-neural-network.html"><i class="fa fa-check"></i><b>4</b> Artificial Neural Network</a>
<ul>
<li class="chapter" data-level="" data-path="artificial-neural-network.html"><a href="artificial-neural-network.html#r-packages-and-setup-2"><i class="fa fa-check"></i>R Packages and Setup</a></li>
<li class="chapter" data-level="4.1" data-path="artificial-neural-network.html"><a href="artificial-neural-network.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="artificial-neural-network.html"><a href="artificial-neural-network.html#load-data-1"><i class="fa fa-check"></i><b>4.2</b> Load Data</a></li>
<li class="chapter" data-level="4.3" data-path="artificial-neural-network.html"><a href="artificial-neural-network.html#model-ann"><i class="fa fa-check"></i><b>4.3</b> Model ANN</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="artificial-neural-network.html"><a href="artificial-neural-network.html#simple-ann"><i class="fa fa-check"></i><b>4.3.1</b> Simple ANN</a></li>
<li class="chapter" data-level="4.3.2" data-path="artificial-neural-network.html"><a href="artificial-neural-network.html#complex-ann"><i class="fa fa-check"></i><b>4.3.2</b> Complex ANN</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="artificial-neural-network.html"><a href="artificial-neural-network.html#evaluate-ann"><i class="fa fa-check"></i><b>4.4</b> Evaluate ANN</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="artificial-neural-network.html"><a href="artificial-neural-network.html#simple-ann-1"><i class="fa fa-check"></i><b>4.4.1</b> Simple ANN</a></li>
<li class="chapter" data-level="4.4.2" data-path="artificial-neural-network.html"><a href="artificial-neural-network.html#complex-ann-1"><i class="fa fa-check"></i><b>4.4.2</b> Complex ANN</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html"><i class="fa fa-check"></i><b>5</b> Footnotes and citations</a>
<ul>
<li class="chapter" data-level="5.1" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html#footnotes"><i class="fa fa-check"></i><b>5.1</b> Footnotes</a></li>
<li class="chapter" data-level="5.2" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html#citations"><i class="fa fa-check"></i><b>5.2</b> Citations</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="blocks.html"><a href="blocks.html"><i class="fa fa-check"></i><b>6</b> Blocks</a>
<ul>
<li class="chapter" data-level="6.1" data-path="blocks.html"><a href="blocks.html#equations"><i class="fa fa-check"></i><b>6.1</b> Equations</a></li>
<li class="chapter" data-level="6.2" data-path="blocks.html"><a href="blocks.html#theorems-and-proofs"><i class="fa fa-check"></i><b>6.2</b> Theorems and proofs</a></li>
<li class="chapter" data-level="6.3" data-path="blocks.html"><a href="blocks.html#callout-blocks"><i class="fa fa-check"></i><b>6.3</b> Callout blocks</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="sharing-your-book.html"><a href="sharing-your-book.html"><i class="fa fa-check"></i><b>7</b> Sharing your book</a>
<ul>
<li class="chapter" data-level="7.1" data-path="sharing-your-book.html"><a href="sharing-your-book.html#publishing"><i class="fa fa-check"></i><b>7.1</b> Publishing</a></li>
<li class="chapter" data-level="7.2" data-path="sharing-your-book.html"><a href="sharing-your-book.html#pages"><i class="fa fa-check"></i><b>7.2</b> 404 pages</a></li>
<li class="chapter" data-level="7.3" data-path="sharing-your-book.html"><a href="sharing-your-book.html#metadata-for-sharing"><i class="fa fa-check"></i><b>7.3</b> Metadata for sharing</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://michiganross.umich.edu/courses/advanced-big-data-analytics-10562">About The Course</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Indirect Obesity Forecasting</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="artificial-neural-network" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Artificial Neural Network<a href="artificial-neural-network.html#artificial-neural-network" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="r-packages-and-setup-2" class="section level2 unnumbered hasAnchor">
<h2>R Packages and Setup<a href="artificial-neural-network.html#r-packages-and-setup-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="introduction-2" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Introduction<a href="artificial-neural-network.html#introduction-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Below paragraph is copied from the assignment, we are planning on updating this as we formulate our narrative for the final deliverable:</p>
<p>Artificial Neural Networks (ANNs) are modeled after the human brain and capable of learning and improving from experience. One strength is their ability to adapt to complex patterns and relationships in high-dimensional data, making them powerful tools for our dataset. However, ANNs require large amounts of training data and computational resources, which can make implementation time-consuming and resource-intensive.</p>
<p>We will now attempt using an ANN. Despite being considered a ‘black box’ model due to its difficulty in interpreting decision-making processes compared to models like DT, ANNs may perform slightly better than LR in terms of accuracy.</p>
</div>
<div id="load-data-1" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Load Data<a href="artificial-neural-network.html#load-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="artificial-neural-network.html#cb1-1" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb1-2"><a href="artificial-neural-network.html#cb1-2" tabindex="-1"></a>train_ann <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;../Train Test Set/train_ann.csv&#39;</span>)</span>
<span id="cb1-3"><a href="artificial-neural-network.html#cb1-3" tabindex="-1"></a>test_ann <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;../Train Test Set/test_ann.csv&#39;</span>)</span>
<span id="cb1-4"><a href="artificial-neural-network.html#cb1-4" tabindex="-1"></a></span>
<span id="cb1-5"><a href="artificial-neural-network.html#cb1-5" tabindex="-1"></a><span class="co"># Display statistics</span></span>
<span id="cb1-6"><a href="artificial-neural-network.html#cb1-6" tabindex="-1"></a><span class="fu">str</span>(train_ann)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    10379 obs. of  27 variables:
##  $ gender_female                  : int  1 1 1 0 1 1 1 0 1 1 ...
##  $ gender_male                    : int  0 0 0 1 0 0 0 1 0 0 ...
##  $ age                            : num  0.213 0.426 0.106 0.106 0.234 ...
##  $ fam_history_overweight1        : int  1 1 1 1 1 1 1 1 1 0 ...
##  $ freq_consumption_hc_food1      : int  1 1 1 1 1 1 0 1 1 0 ...
##  $ veg_freq                       : num  1 0.552 1 1 1 ...
##  $ num_meals                      : num  0.667 0.659 0.667 0.667 0.667 ...
##  $ food_between_meals_frequently  : int  0 0 0 0 0 0 0 0 0 1 ...
##  $ food_between_meals_never       : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ food_between_meals_sometimes   : int  1 1 1 0 1 1 1 1 1 0 ...
##  $ smoke1                         : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ water_daily                    : num  0.736 0.482 0.933 1 0.932 ...
##  $ caloric_beverages1             : int  0 0 0 1 0 0 0 0 0 0 ...
##  $ activity_freq                  : num  0.0557 0.3292 0.4882 1 0.0883 ...
##  $ tech_use                       : num  0.243 0 0.328 0 0.337 ...
##  $ alcohol_never                  : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ alcohol_sometimes              : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ transport_bike                 : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ transport_motorbike            : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ transport_public_transportation: int  1 0 1 1 1 1 1 1 1 1 ...
##  $ transport_walking              : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ eating_habit_binary            : num  0.833 0.68 0.833 0.833 0.833 ...
##  $ physical_activity_binary       : num  0.336 0.598 0.562 1 0.318 ...
##  $ age_group_young_adult          : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ age_group_adult                : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ age_group_senior               : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ obesity_leveloverweight        : int  1 1 1 1 1 1 1 1 1 0 ...</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="artificial-neural-network.html#cb3-1" tabindex="-1"></a><span class="fu">summary</span>(train_ann)</span></code></pre></div>
<pre><code>##  gender_female     gender_male          age         fam_history_overweight1
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000         
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.1277   1st Qu.:1.0000         
##  Median :1.0000   Median :0.0000   Median :0.1915   Median :1.0000         
##  Mean   :0.5079   Mean   :0.4921   Mean   :0.2087   Mean   :0.8177         
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.2553   3rd Qu.:1.0000         
##  Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000         
##  freq_consumption_hc_food1    veg_freq        num_meals     
##  Min.   :0.0000            Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:1.0000            1st Qu.:0.5000   1st Qu.:0.6667  
##  Median :1.0000            Median :0.7223   Median :0.6667  
##  Mean   :0.9166            Mean   :0.7260   Mean   :0.5858  
##  3rd Qu.:1.0000            3rd Qu.:1.0000   3rd Qu.:0.6667  
##  Max.   :1.0000            Max.   :1.0000   Max.   :1.0000  
##  food_between_meals_frequently food_between_meals_never
##  Min.   :0.0000                Min.   :0.00000         
##  1st Qu.:0.0000                1st Qu.:0.00000         
##  Median :0.0000                Median :0.00000         
##  Mean   :0.1212                Mean   :0.01253         
##  3rd Qu.:0.0000                3rd Qu.:0.00000         
##  Max.   :1.0000                Max.   :1.00000         
##  food_between_meals_sometimes     smoke1         water_daily    
##  Min.   :0.0000               Min.   :0.00000   Min.   :0.0000  
##  1st Qu.:1.0000               1st Qu.:0.00000   1st Qu.:0.3981  
##  Median :1.0000               Median :0.00000   Median :0.5000  
##  Mean   :0.8446               Mean   :0.01224   Mean   :0.5146  
##  3rd Qu.:1.0000               3rd Qu.:0.00000   3rd Qu.:0.7678  
##  Max.   :1.0000               Max.   :1.00000   Max.   :1.0000  
##  caloric_beverages1 activity_freq        tech_use      alcohol_never   
##  Min.   :0.00000    Min.   :0.00000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.00000    1st Qu.:0.00235   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :0.00000    Median :0.33333   Median :0.2870   Median :0.0000  
##  Mean   :0.03276    Mean   :0.32699   Mean   :0.3074   Mean   :0.2461  
##  3rd Qu.:0.00000    3rd Qu.:0.52884   3rd Qu.:0.5000   3rd Qu.:0.0000  
##  Max.   :1.00000    Max.   :1.00000   Max.   :1.0000   Max.   :1.0000  
##  alcohol_sometimes transport_bike     transport_motorbike
##  Min.   :0.0000    Min.   :0.000000   Min.   :0.000000   
##  1st Qu.:0.0000    1st Qu.:0.000000   1st Qu.:0.000000   
##  Median :1.0000    Median :0.000000   Median :0.000000   
##  Mean   :0.7289    Mean   :0.001734   Mean   :0.001927   
##  3rd Qu.:1.0000    3rd Qu.:0.000000   3rd Qu.:0.000000   
##  Max.   :1.0000    Max.   :1.000000   Max.   :1.000000   
##  transport_public_transportation transport_walking eating_habit_binary
##  Min.   :0.0000                  Min.   :0.00000   Min.   :0.0000     
##  1st Qu.:1.0000                  1st Qu.:0.00000   1st Qu.:0.6546     
##  Median :1.0000                  Median :0.00000   Median :0.6667     
##  Mean   :0.8056                  Mean   :0.02226   Mean   :0.6877     
##  3rd Qu.:1.0000                  3rd Qu.:0.00000   3rd Qu.:0.8333     
##  Max.   :1.0000                  Max.   :1.00000   Max.   :1.0000     
##  physical_activity_binary age_group_young_adult age_group_adult  
##  Min.   :0.0000           Min.   :0.0000        Min.   :0.00000  
##  1st Qu.:0.3442           1st Qu.:1.0000        1st Qu.:0.00000  
##  Median :0.4573           Median :1.0000        Median :0.00000  
##  Mean   :0.4732           Mean   :0.9019        Mean   :0.05222  
##  3rd Qu.:0.6000           3rd Qu.:1.0000        3rd Qu.:0.00000  
##  Max.   :1.0000           Max.   :1.0000        Max.   :1.00000  
##  age_group_senior   obesity_leveloverweight
##  Min.   :0.000000   Min.   :0.0000         
##  1st Qu.:0.000000   1st Qu.:0.0000         
##  Median :0.000000   Median :1.0000         
##  Mean   :0.003276   Mean   :0.7262         
##  3rd Qu.:0.000000   3rd Qu.:1.0000         
##  Max.   :1.000000   Max.   :1.0000</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="artificial-neural-network.html#cb5-1" tabindex="-1"></a><span class="fu">head</span>(train_ann)</span></code></pre></div>
<pre><code>##   gender_female gender_male       age fam_history_overweight1
## 1             1           0 0.2127660                       1
## 2             1           0 0.4255319                       1
## 3             1           0 0.1063830                       1
## 4             0           1 0.1063830                       1
## 5             1           0 0.2340426                       1
## 6             1           0 0.2553191                       1
##   freq_consumption_hc_food1  veg_freq num_meals food_between_meals_frequently
## 1                         1 1.0000000 0.6666667                             0
## 2                         1 0.5516675 0.6593030                             0
## 3                         1 1.0000000 0.6666667                             0
## 4                         1 1.0000000 0.6666667                             0
## 5                         1 1.0000000 0.6666667                             0
## 6                         1 1.0000000 0.6666667                             0
##   food_between_meals_never food_between_meals_sometimes smoke1 water_daily
## 1                        0                            1      0   0.7364515
## 2                        0                            1      0   0.4822175
## 3                        0                            1      0   0.9327950
## 4                        0                            0      0   1.0000000
## 5                        0                            1      0   0.9317565
## 6                        0                            1      0   0.1737795
##   caloric_beverages1 activity_freq  tech_use alcohol_never alcohol_sometimes
## 1                  0    0.05569533 0.2434340             0                 1
## 2                  0    0.32917367 0.0000000             0                 1
## 3                  0    0.48822467 0.3277855             0                 1
## 4                  1    1.00000000 0.0000000             0                 1
## 5                  0    0.08827700 0.3366050             0                 1
## 6                  0    0.07248500 0.3126750             0                 1
##   transport_bike transport_motorbike transport_public_transportation
## 1              0                   0                               1
## 2              0                   0                               0
## 3              0                   0                               1
## 4              0                   0                               1
## 5              0                   0                               1
## 6              0                   0                               1
##   transport_walking eating_habit_binary physical_activity_binary
## 1                 0           0.8333333                0.3360436
## 2                 0           0.6802073                0.5975042
## 3                 0           0.8333333                0.5618206
## 4                 0           0.8333333                1.0000000
## 5                 0           0.8333333                0.3183242
## 6                 0           0.8333333                0.3184210
##   age_group_young_adult age_group_adult age_group_senior
## 1                     1               0                0
## 2                     1               0                0
## 3                     1               0                0
## 4                     1               0                0
## 5                     1               0                0
## 6                     1               0                0
##   obesity_leveloverweight
## 1                       1
## 2                       1
## 3                       1
## 4                       1
## 5                       1
## 6                       1</code></pre>
</div>
<div id="model-ann" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Model ANN<a href="artificial-neural-network.html#model-ann" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="simple-ann" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Simple ANN<a href="artificial-neural-network.html#simple-ann" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will initiate with a single neuron (single node) ANN to run a preliminary simple model. Once we have finished working on that model, we will create a more complex model consisting of one hidden layer and one neuron.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="artificial-neural-network.html#cb7-1" tabindex="-1"></a><span class="co"># Build a model</span></span>
<span id="cb7-2"><a href="artificial-neural-network.html#cb7-2" tabindex="-1"></a>model_ann <span class="ot">&lt;-</span> <span class="fu">neuralnet</span>(obesity_leveloverweight <span class="sc">~</span> .,</span>
<span id="cb7-3"><a href="artificial-neural-network.html#cb7-3" tabindex="-1"></a>                       <span class="at">data =</span> train_ann,</span>
<span id="cb7-4"><a href="artificial-neural-network.html#cb7-4" tabindex="-1"></a>                       <span class="at">hidden =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="artificial-neural-network.html#cb8-1" tabindex="-1"></a><span class="co"># Display summary</span></span>
<span id="cb8-2"><a href="artificial-neural-network.html#cb8-2" tabindex="-1"></a><span class="fu">summary</span>(model_ann)</span></code></pre></div>
<pre><code>##                     Length Class      Mode    
## call                     4 -none-     call    
## response             10379 -none-     numeric 
## covariate           269854 -none-     numeric 
## model.list               2 -none-     list    
## err.fct                  1 -none-     function
## act.fct                  1 -none-     function
## linear.output            1 -none-     logical 
## data                    27 data.frame list    
## exclude                  0 -none-     NULL    
## net.result               1 -none-     list    
## weights                  1 -none-     list    
## generalized.weights      1 -none-     list    
## startweights             1 -none-     list    
## result.matrix           32 -none-     numeric</code></pre>
</div>
<div id="complex-ann" class="section level3 hasAnchor" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Complex ANN<a href="artificial-neural-network.html#complex-ann" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Adding hidden layers increases computational requirements, so this will take significantly longer to run compared to a simple ANN.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="artificial-neural-network.html#cb10-1" tabindex="-1"></a><span class="co"># Build a complex model</span></span>
<span id="cb10-2"><a href="artificial-neural-network.html#cb10-2" tabindex="-1"></a>model_ann_complex <span class="ot">&lt;-</span> <span class="fu">neuralnet</span>(obesity_leveloverweight <span class="sc">~</span> .,</span>
<span id="cb10-3"><a href="artificial-neural-network.html#cb10-3" tabindex="-1"></a>                               <span class="at">data =</span> train_ann,</span>
<span id="cb10-4"><a href="artificial-neural-network.html#cb10-4" tabindex="-1"></a>                               <span class="at">hidden =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="artificial-neural-network.html#cb11-1" tabindex="-1"></a><span class="co"># Display summary</span></span>
<span id="cb11-2"><a href="artificial-neural-network.html#cb11-2" tabindex="-1"></a><span class="fu">summary</span>(model_ann_complex)</span></code></pre></div>
<pre><code>##                     Length Class      Mode    
## call                     4 -none-     call    
## response             10379 -none-     numeric 
## covariate           269854 -none-     numeric 
## model.list               2 -none-     list    
## err.fct                  1 -none-     function
## act.fct                  1 -none-     function
## linear.output            1 -none-     logical 
## data                    27 data.frame list    
## exclude                  0 -none-     NULL    
## net.result               1 -none-     list    
## weights                  1 -none-     list    
## generalized.weights      1 -none-     list    
## startweights             1 -none-     list    
## result.matrix           34 -none-     numeric</code></pre>
</div>
</div>
<div id="evaluate-ann" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Evaluate ANN<a href="artificial-neural-network.html#evaluate-ann" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="simple-ann-1" class="section level3 hasAnchor" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Simple ANN<a href="artificial-neural-network.html#simple-ann-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="artificial-neural-network.html#cb13-1" tabindex="-1"></a><span class="co"># Make a prediction</span></span>
<span id="cb13-2"><a href="artificial-neural-network.html#cb13-2" tabindex="-1"></a>prediction_ann_probability <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_ann, test_ann)</span>
<span id="cb13-3"><a href="artificial-neural-network.html#cb13-3" tabindex="-1"></a>prediction_ann <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(prediction_ann_probability <span class="sc">&gt;=</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb13-4"><a href="artificial-neural-network.html#cb13-4" tabindex="-1"></a><span class="fu">summary</span>(prediction_ann_probability)</span></code></pre></div>
<pre><code>##        V1         
##  Min.   :0.08716  
##  1st Qu.:0.53689  
##  Median :0.90026  
##  Mean   :0.73204  
##  3rd Qu.:0.97783  
##  Max.   :1.00254</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="artificial-neural-network.html#cb15-1" tabindex="-1"></a><span class="co"># Perform confusion matrix</span></span>
<span id="cb15-2"><a href="artificial-neural-network.html#cb15-2" tabindex="-1"></a>cm_ann <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(prediction_ann),</span>
<span id="cb15-3"><a href="artificial-neural-network.html#cb15-3" tabindex="-1"></a>                          <span class="fu">as.factor</span>(test_ann<span class="sc">$</span>obesity_leveloverweight),</span>
<span id="cb15-4"><a href="artificial-neural-network.html#cb15-4" tabindex="-1"></a>                          <span class="at">positive =</span> <span class="st">&#39;1&#39;</span>)</span>
<span id="cb15-5"><a href="artificial-neural-network.html#cb15-5" tabindex="-1"></a>cm_ann</span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    0    1
##          0 1938  560
##          1  825 7056
##                                          
##                Accuracy : 0.8666         
##                  95% CI : (0.8599, 0.873)
##     No Information Rate : 0.7338         
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16      
##                                          
##                   Kappa : 0.6477         
##                                          
##  Mcnemar&#39;s Test P-Value : 1.305e-12      
##                                          
##             Sensitivity : 0.9265         
##             Specificity : 0.7014         
##          Pos Pred Value : 0.8953         
##          Neg Pred Value : 0.7758         
##              Prevalence : 0.7338         
##          Detection Rate : 0.6798         
##    Detection Prevalence : 0.7593         
##       Balanced Accuracy : 0.8139         
##                                          
##        &#39;Positive&#39; Class : 1              
## </code></pre>
<p>Based on the confusion matrix, we observe that the model achieves an accuracy of <code>0.8666</code>, sensitivity of <code>0.9265</code>, and a Kappa coefficient of <code>0.6477</code>. We will assess these results towards the conclusion of the assignment when we have completed stacked models.</p>
</div>
<div id="complex-ann-1" class="section level3 hasAnchor" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> Complex ANN<a href="artificial-neural-network.html#complex-ann-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="artificial-neural-network.html#cb17-1" tabindex="-1"></a><span class="co"># Make a prediction</span></span>
<span id="cb17-2"><a href="artificial-neural-network.html#cb17-2" tabindex="-1"></a>prediction_ann_complex_probability <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_ann_complex, test_ann)</span>
<span id="cb17-3"><a href="artificial-neural-network.html#cb17-3" tabindex="-1"></a>prediction_ann_complex <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(prediction_ann_complex_probability <span class="sc">&gt;=</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb17-4"><a href="artificial-neural-network.html#cb17-4" tabindex="-1"></a><span class="fu">summary</span>(prediction_ann_complex_probability)</span></code></pre></div>
<pre><code>##        V1        
##  Min.   :0.0472  
##  1st Qu.:0.5127  
##  Median :0.9188  
##  Mean   :0.7317  
##  3rd Qu.:0.9782  
##  Max.   :0.9799</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="artificial-neural-network.html#cb19-1" tabindex="-1"></a><span class="co"># Perform confusion matrix</span></span>
<span id="cb19-2"><a href="artificial-neural-network.html#cb19-2" tabindex="-1"></a>cm_ann_complex <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(prediction_ann_complex),</span>
<span id="cb19-3"><a href="artificial-neural-network.html#cb19-3" tabindex="-1"></a>                                  <span class="fu">as.factor</span>(test_ann<span class="sc">$</span>obesity_leveloverweight),</span>
<span id="cb19-4"><a href="artificial-neural-network.html#cb19-4" tabindex="-1"></a>                                  <span class="at">positive =</span> <span class="st">&#39;1&#39;</span>)</span>
<span id="cb19-5"><a href="artificial-neural-network.html#cb19-5" tabindex="-1"></a>cm_ann_complex</span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    0    1
##          0 1971  593
##          1  792 7023
##                                          
##                Accuracy : 0.8666         
##                  95% CI : (0.8599, 0.873)
##     No Information Rate : 0.7338         
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16      
##                                          
##                   Kappa : 0.6504         
##                                          
##  Mcnemar&#39;s Test P-Value : 1.036e-07      
##                                          
##             Sensitivity : 0.9221         
##             Specificity : 0.7134         
##          Pos Pred Value : 0.8987         
##          Neg Pred Value : 0.7687         
##              Prevalence : 0.7338         
##          Detection Rate : 0.6767         
##    Detection Prevalence : 0.7530         
##       Balanced Accuracy : 0.8177         
##                                          
##        &#39;Positive&#39; Class : 1              
## </code></pre>
<p>Based on the confusion matrix, we observe that the model achieves an accuracy of <code>0.8666</code>, sensitivity of <code>0.9221</code>, and a Kappa coefficient of <code>0.6504</code>. We will assess these results towards the conclusion of the assignment when we have completed stacked models.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="footnotes-and-citations.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
