<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Decision Tree (DT) | Indirect Obesity Forecasting</title>
  <meta name="description" content="This is our team project for TO628. In this project, we are exploring innovative predictive analytics methods to assess and manage obesity in the context of potential government-imposed BMI usage restrictions. Utilizing the Proxy Health Evaluation System (PHES), our approach circumvents these potential limitations, providing health insurance companies and medical professionals with essential insights to develop proactive health programs and enhance patient outcomes." />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Decision Tree (DT) | Indirect Obesity Forecasting" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is our team project for TO628. In this project, we are exploring innovative predictive analytics methods to assess and manage obesity in the context of potential government-imposed BMI usage restrictions. Utilizing the Proxy Health Evaluation System (PHES), our approach circumvents these potential limitations, providing health insurance companies and medical professionals with essential insights to develop proactive health programs and enhance patient outcomes." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Decision Tree (DT) | Indirect Obesity Forecasting" />
  
  <meta name="twitter:description" content="This is our team project for TO628. In this project, we are exploring innovative predictive analytics methods to assess and manage obesity in the context of potential government-imposed BMI usage restrictions. Utilizing the Proxy Health Evaluation System (PHES), our approach circumvents these potential limitations, providing health insurance companies and medical professionals with essential insights to develop proactive health programs and enhance patient outcomes." />
  

<meta name="author" content="Aaron Zhao" />
<meta name="author" content="Arneet Singh" />
<meta name="author" content="Blake Waldman" />
<meta name="author" content="Grace Coleman" />
<meta name="author" content="Tyler James Phillips" />
<meta name="author" content="Yousuf Altameemi" />


<meta name="date" content="2024-04-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="k-neareast-neighbor-knn.html"/>
<link rel="next" href="support-vector-machine-svm.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="_bookdown_files/to_628_hidden_image2.jpg" 
alt="TO 628 Group Project" 
title="TO 628 Group Project" style="width:100%;"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#dataset-overview"><i class="fa fa-check"></i>Dataset Overview</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#audience-and-impact"><i class="fa fa-check"></i>Audience and Impact</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#challenges-in-health-insurance"><i class="fa fa-check"></i>Challenges in Health Insurance</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#medical-professional-engagement"><i class="fa fa-check"></i>Medical Professional Engagement</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#research-questions"><i class="fa fa-check"></i>Research Questions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#adoption-and-implementation"><i class="fa fa-check"></i>Adoption and Implementation</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#strategic-impact"><i class="fa fa-check"></i>Strategic Impact</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="initial-analysis.html"><a href="initial-analysis.html"><i class="fa fa-check"></i><b>2</b> Initial Analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="initial-analysis.html"><a href="initial-analysis.html#load-data"><i class="fa fa-check"></i><b>2.1</b> Load Data</a></li>
<li class="chapter" data-level="2.2" data-path="initial-analysis.html"><a href="initial-analysis.html#clean-data"><i class="fa fa-check"></i><b>2.2</b> Clean Data</a></li>
<li class="chapter" data-level="2.3" data-path="initial-analysis.html"><a href="initial-analysis.html#feature-engineering"><i class="fa fa-check"></i><b>2.3</b> Feature Engineering</a></li>
<li class="chapter" data-level="2.4" data-path="initial-analysis.html"><a href="initial-analysis.html#visualize-data"><i class="fa fa-check"></i><b>2.4</b> Visualize Data</a></li>
<li class="chapter" data-level="2.5" data-path="initial-analysis.html"><a href="initial-analysis.html#split-data"><i class="fa fa-check"></i><b>2.5</b> Split Data</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="initial-analysis.html"><a href="initial-analysis.html#split-train-test"><i class="fa fa-check"></i><b>2.5.1</b> Split Train Test</a></li>
<li class="chapter" data-level="2.5.2" data-path="initial-analysis.html"><a href="initial-analysis.html#split-lr"><i class="fa fa-check"></i><b>2.5.2</b> Split LR</a></li>
<li class="chapter" data-level="2.5.3" data-path="initial-analysis.html"><a href="initial-analysis.html#split-dt"><i class="fa fa-check"></i><b>2.5.3</b> Split DT</a></li>
<li class="chapter" data-level="2.5.4" data-path="initial-analysis.html"><a href="initial-analysis.html#split-svm"><i class="fa fa-check"></i><b>2.5.4</b> Split SVM</a></li>
<li class="chapter" data-level="2.5.5" data-path="initial-analysis.html"><a href="initial-analysis.html#split-rf"><i class="fa fa-check"></i><b>2.5.5</b> Split RF</a></li>
<li class="chapter" data-level="2.5.6" data-path="initial-analysis.html"><a href="initial-analysis.html#split-xgb"><i class="fa fa-check"></i><b>2.5.6</b> Split XGB</a></li>
<li class="chapter" data-level="2.5.7" data-path="initial-analysis.html"><a href="initial-analysis.html#split-ann"><i class="fa fa-check"></i><b>2.5.7</b> Split ANN</a></li>
<li class="chapter" data-level="2.5.8" data-path="initial-analysis.html"><a href="initial-analysis.html#split-knn"><i class="fa fa-check"></i><b>2.5.8</b> Split KNN</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="logistic-regression-lr.html"><a href="logistic-regression-lr.html"><i class="fa fa-check"></i><b>3</b> Logistic Regression (LR)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="logistic-regression-lr.html"><a href="logistic-regression-lr.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="logistic-regression-lr.html"><a href="logistic-regression-lr.html#load-data-1"><i class="fa fa-check"></i><b>3.2</b> Load Data</a></li>
<li class="chapter" data-level="3.3" data-path="logistic-regression-lr.html"><a href="logistic-regression-lr.html#model-lr"><i class="fa fa-check"></i><b>3.3</b> Model LR</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="logistic-regression-lr.html"><a href="logistic-regression-lr.html#simple-lr"><i class="fa fa-check"></i><b>3.3.1</b> Simple LR</a></li>
<li class="chapter" data-level="3.3.2" data-path="logistic-regression-lr.html"><a href="logistic-regression-lr.html#complex-lr"><i class="fa fa-check"></i><b>3.3.2</b> Complex LR</a></li>
<li class="chapter" data-level="3.3.3" data-path="logistic-regression-lr.html"><a href="logistic-regression-lr.html#stepwise-lr"><i class="fa fa-check"></i><b>3.3.3</b> Stepwise LR</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="logistic-regression-lr.html"><a href="logistic-regression-lr.html#evaluate-lr"><i class="fa fa-check"></i><b>3.4</b> Evaluate LR</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="logistic-regression-lr.html"><a href="logistic-regression-lr.html#simple-lr-1"><i class="fa fa-check"></i><b>3.4.1</b> Simple LR</a></li>
<li class="chapter" data-level="3.4.2" data-path="logistic-regression-lr.html"><a href="logistic-regression-lr.html#complex-lr-1"><i class="fa fa-check"></i><b>3.4.2</b> Complex LR</a></li>
<li class="chapter" data-level="3.4.3" data-path="logistic-regression-lr.html"><a href="logistic-regression-lr.html#stepwise-lr-1"><i class="fa fa-check"></i><b>3.4.3</b> Stepwise LR</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="artificial-neural-network-ann.html"><a href="artificial-neural-network-ann.html"><i class="fa fa-check"></i><b>4</b> Artificial Neural Network (ANN)</a>
<ul>
<li class="chapter" data-level="4.1" data-path="artificial-neural-network-ann.html"><a href="artificial-neural-network-ann.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="artificial-neural-network-ann.html"><a href="artificial-neural-network-ann.html#load-data-2"><i class="fa fa-check"></i><b>4.2</b> Load Data</a></li>
<li class="chapter" data-level="4.3" data-path="artificial-neural-network-ann.html"><a href="artificial-neural-network-ann.html#model-ann"><i class="fa fa-check"></i><b>4.3</b> Model ANN</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="artificial-neural-network-ann.html"><a href="artificial-neural-network-ann.html#simple-ann"><i class="fa fa-check"></i><b>4.3.1</b> Simple ANN</a></li>
<li class="chapter" data-level="4.3.2" data-path="artificial-neural-network-ann.html"><a href="artificial-neural-network-ann.html#complex-ann"><i class="fa fa-check"></i><b>4.3.2</b> Complex ANN</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="artificial-neural-network-ann.html"><a href="artificial-neural-network-ann.html#evaluate-ann"><i class="fa fa-check"></i><b>4.4</b> Evaluate ANN</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="artificial-neural-network-ann.html"><a href="artificial-neural-network-ann.html#simple-ann-1"><i class="fa fa-check"></i><b>4.4.1</b> Simple ANN</a></li>
<li class="chapter" data-level="4.4.2" data-path="artificial-neural-network-ann.html"><a href="artificial-neural-network-ann.html#complex-ann-1"><i class="fa fa-check"></i><b>4.4.2</b> Complex ANN</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="k-neareast-neighbor-knn.html"><a href="k-neareast-neighbor-knn.html"><i class="fa fa-check"></i><b>5</b> K-Neareast Neighbor (KNN)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="k-neareast-neighbor-knn.html"><a href="k-neareast-neighbor-knn.html#introduction-3"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="k-neareast-neighbor-knn.html"><a href="k-neareast-neighbor-knn.html#load-data-3"><i class="fa fa-check"></i><b>5.2</b> Load Data</a></li>
<li class="chapter" data-level="5.3" data-path="k-neareast-neighbor-knn.html"><a href="k-neareast-neighbor-knn.html#model-knn"><i class="fa fa-check"></i><b>5.3</b> Model KNN</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="k-neareast-neighbor-knn.html"><a href="k-neareast-neighbor-knn.html#default-knn"><i class="fa fa-check"></i><b>5.3.1</b> Default KNN</a></li>
<li class="chapter" data-level="5.3.2" data-path="k-neareast-neighbor-knn.html"><a href="k-neareast-neighbor-knn.html#tuned-knn"><i class="fa fa-check"></i><b>5.3.2</b> Tuned KNN</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="k-neareast-neighbor-knn.html"><a href="k-neareast-neighbor-knn.html#evaluate-knn"><i class="fa fa-check"></i><b>5.4</b> Evaluate KNN</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="k-neareast-neighbor-knn.html"><a href="k-neareast-neighbor-knn.html#default-knn-1"><i class="fa fa-check"></i><b>5.4.1</b> Default KNN</a></li>
<li class="chapter" data-level="5.4.2" data-path="k-neareast-neighbor-knn.html"><a href="k-neareast-neighbor-knn.html#tuned-knn-1"><i class="fa fa-check"></i><b>5.4.2</b> Tuned KNN</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="decision-tree-dt.html"><a href="decision-tree-dt.html"><i class="fa fa-check"></i><b>6</b> Decision Tree (DT)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="decision-tree-dt.html"><a href="decision-tree-dt.html#introduction-4"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="decision-tree-dt.html"><a href="decision-tree-dt.html#load-data-4"><i class="fa fa-check"></i><b>6.2</b> Load Data</a></li>
<li class="chapter" data-level="6.3" data-path="decision-tree-dt.html"><a href="decision-tree-dt.html#model-dt"><i class="fa fa-check"></i><b>6.3</b> Model DT</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="decision-tree-dt.html"><a href="decision-tree-dt.html#simple-dt"><i class="fa fa-check"></i><b>6.3.1</b> Simple DT</a></li>
<li class="chapter" data-level="6.3.2" data-path="decision-tree-dt.html"><a href="decision-tree-dt.html#dt-with-cost-matrix"><i class="fa fa-check"></i><b>6.3.2</b> DT with Cost Matrix</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="decision-tree-dt.html"><a href="decision-tree-dt.html#evaluate-dt"><i class="fa fa-check"></i><b>6.4</b> Evaluate DT</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="decision-tree-dt.html"><a href="decision-tree-dt.html#simple-dt-1"><i class="fa fa-check"></i><b>6.4.1</b> Simple DT</a></li>
<li class="chapter" data-level="6.4.2" data-path="decision-tree-dt.html"><a href="decision-tree-dt.html#dt-with-cost-matrix-1"><i class="fa fa-check"></i><b>6.4.2</b> DT with Cost Matrix</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="support-vector-machine-svm.html"><a href="support-vector-machine-svm.html"><i class="fa fa-check"></i><b>7</b> Support Vector Machine (SVM)</a>
<ul>
<li class="chapter" data-level="7.1" data-path="support-vector-machine-svm.html"><a href="support-vector-machine-svm.html#introduction-5"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="support-vector-machine-svm.html"><a href="support-vector-machine-svm.html#load-data-5"><i class="fa fa-check"></i><b>7.2</b> Load Data</a></li>
<li class="chapter" data-level="7.3" data-path="support-vector-machine-svm.html"><a href="support-vector-machine-svm.html#model-svm"><i class="fa fa-check"></i><b>7.3</b> Model SVM</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="support-vector-machine-svm.html"><a href="support-vector-machine-svm.html#vanilla-svm"><i class="fa fa-check"></i><b>7.3.1</b> Vanilla SVM</a></li>
<li class="chapter" data-level="7.3.2" data-path="support-vector-machine-svm.html"><a href="support-vector-machine-svm.html#rbf-svm"><i class="fa fa-check"></i><b>7.3.2</b> RBF SVM</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="support-vector-machine-svm.html"><a href="support-vector-machine-svm.html#evaluate-svm"><i class="fa fa-check"></i><b>7.4</b> Evaluate SVM</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="support-vector-machine-svm.html"><a href="support-vector-machine-svm.html#vanilla-svm-1"><i class="fa fa-check"></i><b>7.4.1</b> Vanilla SVM</a></li>
<li class="chapter" data-level="7.4.2" data-path="support-vector-machine-svm.html"><a href="support-vector-machine-svm.html#rbf-svm-1"><i class="fa fa-check"></i><b>7.4.2</b> RBF SVM</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="random-forest-rf.html"><a href="random-forest-rf.html"><i class="fa fa-check"></i><b>8</b> Random Forest (RF)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="random-forest-rf.html"><a href="random-forest-rf.html#introduction-6"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="random-forest-rf.html"><a href="random-forest-rf.html#load-data-6"><i class="fa fa-check"></i><b>8.2</b> Load Data</a></li>
<li class="chapter" data-level="8.3" data-path="random-forest-rf.html"><a href="random-forest-rf.html#model-rf"><i class="fa fa-check"></i><b>8.3</b> Model RF</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="random-forest-rf.html"><a href="random-forest-rf.html#simple-rf"><i class="fa fa-check"></i><b>8.3.1</b> Simple RF</a></li>
<li class="chapter" data-level="8.3.2" data-path="random-forest-rf.html"><a href="random-forest-rf.html#tuned-rf"><i class="fa fa-check"></i><b>8.3.2</b> Tuned RF</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="random-forest-rf.html"><a href="random-forest-rf.html#evaluate-rf"><i class="fa fa-check"></i><b>8.4</b> Evaluate RF</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="random-forest-rf.html"><a href="random-forest-rf.html#simple-rf-1"><i class="fa fa-check"></i><b>8.4.1</b> Simple RF</a></li>
<li class="chapter" data-level="8.4.2" data-path="random-forest-rf.html"><a href="random-forest-rf.html#tuned-rf-1"><i class="fa fa-check"></i><b>8.4.2</b> Tuned RF</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="extreme-gradient-boosting-xgb.html"><a href="extreme-gradient-boosting-xgb.html"><i class="fa fa-check"></i><b>9</b> eXtreme Gradient Boosting (XGB)</a>
<ul>
<li class="chapter" data-level="9.1" data-path="extreme-gradient-boosting-xgb.html"><a href="extreme-gradient-boosting-xgb.html#introduction-7"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="extreme-gradient-boosting-xgb.html"><a href="extreme-gradient-boosting-xgb.html#load-data-7"><i class="fa fa-check"></i><b>9.2</b> Load Data</a></li>
<li class="chapter" data-level="9.3" data-path="extreme-gradient-boosting-xgb.html"><a href="extreme-gradient-boosting-xgb.html#model-xgb"><i class="fa fa-check"></i><b>9.3</b> Model XGB</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="extreme-gradient-boosting-xgb.html"><a href="extreme-gradient-boosting-xgb.html#simple-xgb"><i class="fa fa-check"></i><b>9.3.1</b> Simple XGB</a></li>
<li class="chapter" data-level="9.3.2" data-path="extreme-gradient-boosting-xgb.html"><a href="extreme-gradient-boosting-xgb.html#tuned-xgb"><i class="fa fa-check"></i><b>9.3.2</b> Tuned XGB</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="extreme-gradient-boosting-xgb.html"><a href="extreme-gradient-boosting-xgb.html#evaluate-xgb"><i class="fa fa-check"></i><b>9.4</b> Evaluate XGB</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="extreme-gradient-boosting-xgb.html"><a href="extreme-gradient-boosting-xgb.html#simple-xgb-1"><i class="fa fa-check"></i><b>9.4.1</b> Simple XGB</a></li>
<li class="chapter" data-level="9.4.2" data-path="extreme-gradient-boosting-xgb.html"><a href="extreme-gradient-boosting-xgb.html#tuned-xgb-1"><i class="fa fa-check"></i><b>9.4.2</b> Tuned XGB</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="stacked-model-with-decision-tree-sm.html"><a href="stacked-model-with-decision-tree-sm.html"><i class="fa fa-check"></i><b>10</b> Stacked Model with Decision Tree (SM)</a>
<ul>
<li class="chapter" data-level="10.1" data-path="stacked-model-with-decision-tree-sm.html"><a href="stacked-model-with-decision-tree-sm.html#introduction-8"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="stacked-model-with-decision-tree-sm.html"><a href="stacked-model-with-decision-tree-sm.html#load-data-8"><i class="fa fa-check"></i><b>10.2</b> Load Data</a></li>
<li class="chapter" data-level="10.3" data-path="stacked-model-with-decision-tree-sm.html"><a href="stacked-model-with-decision-tree-sm.html#split-data-1"><i class="fa fa-check"></i><b>10.3</b> Split Data</a></li>
<li class="chapter" data-level="10.4" data-path="stacked-model-with-decision-tree-sm.html"><a href="stacked-model-with-decision-tree-sm.html#define-cost-matrix"><i class="fa fa-check"></i><b>10.4</b> Define Cost Matrix</a></li>
<li class="chapter" data-level="10.5" data-path="stacked-model-with-decision-tree-sm.html"><a href="stacked-model-with-decision-tree-sm.html#model-sm"><i class="fa fa-check"></i><b>10.5</b> Model SM</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="stacked-model-with-decision-tree-sm.html"><a href="stacked-model-with-decision-tree-sm.html#simple-sm"><i class="fa fa-check"></i><b>10.5.1</b> Simple SM</a></li>
<li class="chapter" data-level="10.5.2" data-path="stacked-model-with-decision-tree-sm.html"><a href="stacked-model-with-decision-tree-sm.html#sm-with-cost-matrix"><i class="fa fa-check"></i><b>10.5.2</b> SM with Cost Matrix</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="stacked-model-with-decision-tree-sm.html"><a href="stacked-model-with-decision-tree-sm.html#evaluate-sm"><i class="fa fa-check"></i><b>10.6</b> Evaluate SM</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="stacked-model-with-decision-tree-sm.html"><a href="stacked-model-with-decision-tree-sm.html#simple-sm-1"><i class="fa fa-check"></i><b>10.6.1</b> Simple SM</a></li>
<li class="chapter" data-level="10.6.2" data-path="stacked-model-with-decision-tree-sm.html"><a href="stacked-model-with-decision-tree-sm.html#sm-with-cost-matrix-1"><i class="fa fa-check"></i><b>10.6.2</b> SM with Cost Matrix</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="stacked-model-with-decision-tree-sm.html"><a href="stacked-model-with-decision-tree-sm.html#model-evaluations"><i class="fa fa-check"></i><b>10.7</b> Model Evaluations</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>11</b> Conclusion</a>
<ul>
<li class="chapter" data-level="11.1" data-path="conclusion.html"><a href="conclusion.html#takeaways"><i class="fa fa-check"></i><b>11.1</b> Takeaways</a></li>
<li class="chapter" data-level="11.2" data-path="conclusion.html"><a href="conclusion.html#business-impact"><i class="fa fa-check"></i><b>11.2</b> Business Impact</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://michiganross.umich.edu/courses/advanced-big-data-analytics-10562">About The Course</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Indirect Obesity Forecasting</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="decision-tree-dt" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">6</span> Decision Tree (DT)<a href="decision-tree-dt.html#decision-tree-dt" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!-- ## R Packages and Setup {-} -->
<div id="introduction-4" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Introduction<a href="decision-tree-dt.html#introduction-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Decision trees are tree-based models that excel at classification tasks. In contrast, regression trees are effective for continuous outcome predictions rather than distinct classes.</p>
<p>Decision trees structure their decisions based on given features using a tree with one trunk and multiple nodes. Starting from the root node, the tree branches out and makes decisions throughout each step, ultimately outputting predictions at leaves.</p>
<p>Decision trees can easily handle both categorical and numerical data, but they have a tendency to overfit training data, necessitating potential pruning and adjustments. This is why RF or XGB might sometimes yield better results while preventing overfitting.</p>
<p>In our case, decision trees can prove effective for solving our binary classification problem. In this module, we will utilize two models: a basic DT and a DT with a cost-considering cost structure.</p>
</div>
<div id="load-data-4" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Load Data<a href="decision-tree-dt.html#load-data-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="decision-tree-dt.html#cb114-1" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb114-2"><a href="decision-tree-dt.html#cb114-2" tabindex="-1"></a>train_dt <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;Train Test Set/train_dt.csv&#39;</span>)</span>
<span id="cb114-3"><a href="decision-tree-dt.html#cb114-3" tabindex="-1"></a>test_dt <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;Train Test Set/test_dt.csv&#39;</span>)</span>
<span id="cb114-4"><a href="decision-tree-dt.html#cb114-4" tabindex="-1"></a></span>
<span id="cb114-5"><a href="decision-tree-dt.html#cb114-5" tabindex="-1"></a><span class="co"># Display statistics</span></span>
<span id="cb114-6"><a href="decision-tree-dt.html#cb114-6" tabindex="-1"></a><span class="fu">str</span>(train_dt)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    10379 obs. of  27 variables:
##  $ gender_female                  : int  1 1 1 0 1 1 1 0 1 1 ...
##  $ gender_male                    : int  0 0 0 1 0 0 0 1 0 0 ...
##  $ age                            : int  24 34 19 19 25 26 23 27 26 20 ...
##  $ fam_history_overweight1        : int  1 1 1 1 1 1 1 1 1 0 ...
##  $ freq_consumption_hc_food1      : int  1 1 1 1 1 1 0 1 1 0 ...
##  $ veg_freq                       : num  3 2.1 3 3 3 ...
##  $ num_meals                      : num  3 2.98 3 3 3 ...
##  $ food_between_meals_frequently  : int  0 0 0 0 0 0 0 0 0 1 ...
##  $ food_between_meals_never       : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ food_between_meals_sometimes   : int  1 1 1 0 1 1 1 1 1 0 ...
##  $ smoke1                         : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ water_daily                    : num  2.47 1.96 2.87 3 2.86 ...
##  $ caloric_beverages1             : int  0 0 0 1 0 0 0 0 0 0 ...
##  $ activity_freq                  : num  0.167 0.988 1.465 3 0.265 ...
##  $ tech_use                       : num  0.487 0 0.656 0 0.673 ...
##  $ alcohol_never                  : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ alcohol_sometimes              : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ transport_bike                 : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ transport_motorbike            : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ transport_public_transportation: int  1 0 1 1 1 1 1 1 1 1 ...
##  $ transport_walking              : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ obesity_leveloverweight        : int  1 1 1 1 1 1 1 1 1 0 ...
##  $ eating_habit_binary            : num  2.67 2.36 2.67 2.67 2.67 ...
##  $ physical_activity_binary       : num  -0.32 0.988 0.809 3 -0.408 ...
##  $ age_group_young_adult          : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ age_group_adult                : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ age_group_senior               : int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="decision-tree-dt.html#cb116-1" tabindex="-1"></a><span class="fu">summary</span>(train_dt)</span></code></pre></div>
<pre><code>##  gender_female     gender_male          age        fam_history_overweight1
##  Min.   :0.0000   Min.   :0.0000   Min.   :14.00   Min.   :0.0000         
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:20.00   1st Qu.:1.0000         
##  Median :1.0000   Median :0.0000   Median :23.00   Median :1.0000         
##  Mean   :0.5079   Mean   :0.4921   Mean   :23.81   Mean   :0.8177         
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:26.00   3rd Qu.:1.0000         
##  Max.   :1.0000   Max.   :1.0000   Max.   :61.00   Max.   :1.0000         
##  freq_consumption_hc_food1    veg_freq       num_meals    
##  Min.   :0.0000            Min.   :1.000   Min.   :1.000  
##  1st Qu.:1.0000            1st Qu.:2.000   1st Qu.:3.000  
##  Median :1.0000            Median :2.445   Median :3.000  
##  Mean   :0.9166            Mean   :2.452   Mean   :2.758  
##  3rd Qu.:1.0000            3rd Qu.:3.000   3rd Qu.:3.000  
##  Max.   :1.0000            Max.   :3.000   Max.   :4.000  
##  food_between_meals_frequently food_between_meals_never
##  Min.   :0.0000                Min.   :0.00000         
##  1st Qu.:0.0000                1st Qu.:0.00000         
##  Median :0.0000                Median :0.00000         
##  Mean   :0.1212                Mean   :0.01253         
##  3rd Qu.:0.0000                3rd Qu.:0.00000         
##  Max.   :1.0000                Max.   :1.00000         
##  food_between_meals_sometimes     smoke1         water_daily   
##  Min.   :0.0000               Min.   :0.00000   Min.   :1.000  
##  1st Qu.:1.0000               1st Qu.:0.00000   1st Qu.:1.796  
##  Median :1.0000               Median :0.00000   Median :2.000  
##  Mean   :0.8446               Mean   :0.01224   Mean   :2.029  
##  3rd Qu.:1.0000               3rd Qu.:0.00000   3rd Qu.:2.536  
##  Max.   :1.0000               Max.   :1.00000   Max.   :3.000  
##  caloric_beverages1 activity_freq        tech_use      alcohol_never   
##  Min.   :0.00000    Min.   :0.00000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.00000    1st Qu.:0.00705   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :0.00000    Median :1.00000   Median :0.5740   Median :0.0000  
##  Mean   :0.03276    Mean   :0.98097   Mean   :0.6147   Mean   :0.2461  
##  3rd Qu.:0.00000    3rd Qu.:1.58652   3rd Qu.:1.0000   3rd Qu.:0.0000  
##  Max.   :1.00000    Max.   :3.00000   Max.   :2.0000   Max.   :1.0000  
##  alcohol_sometimes transport_bike     transport_motorbike
##  Min.   :0.0000    Min.   :0.000000   Min.   :0.000000   
##  1st Qu.:0.0000    1st Qu.:0.000000   1st Qu.:0.000000   
##  Median :1.0000    Median :0.000000   Median :0.000000   
##  Mean   :0.7289    Mean   :0.001734   Mean   :0.001927   
##  3rd Qu.:1.0000    3rd Qu.:0.000000   3rd Qu.:0.000000   
##  Max.   :1.0000    Max.   :1.000000   Max.   :1.000000   
##  transport_public_transportation transport_walking obesity_leveloverweight
##  Min.   :0.0000                  Min.   :0.00000   Min.   :0.0000         
##  1st Qu.:1.0000                  1st Qu.:0.00000   1st Qu.:0.0000         
##  Median :1.0000                  Median :0.00000   Median :1.0000         
##  Mean   :0.8056                  Mean   :0.02226   Mean   :0.7262         
##  3rd Qu.:1.0000                  3rd Qu.:0.00000   3rd Qu.:1.0000         
##  Max.   :1.0000                  Max.   :1.00000   Max.   :1.0000         
##  eating_habit_binary physical_activity_binary age_group_young_adult
##  Min.   :1.000       Min.   :-2.0000          Min.   :0.0000       
##  1st Qu.:2.309       1st Qu.:-0.2790          1st Qu.:1.0000       
##  Median :2.333       Median : 0.2867          Median :1.0000       
##  Mean   :2.375       Mean   : 0.3662          Mean   :0.9019       
##  3rd Qu.:2.667       3rd Qu.: 1.0000          3rd Qu.:1.0000       
##  Max.   :3.000       Max.   : 3.0000          Max.   :1.0000       
##  age_group_adult   age_group_senior  
##  Min.   :0.00000   Min.   :0.000000  
##  1st Qu.:0.00000   1st Qu.:0.000000  
##  Median :0.00000   Median :0.000000  
##  Mean   :0.05222   Mean   :0.003276  
##  3rd Qu.:0.00000   3rd Qu.:0.000000  
##  Max.   :1.00000   Max.   :1.000000</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="decision-tree-dt.html#cb118-1" tabindex="-1"></a><span class="fu">head</span>(train_dt)</span></code></pre></div>
<pre><code>##   gender_female gender_male age fam_history_overweight1
## 1             1           0  24                       1
## 2             1           0  34                       1
## 3             1           0  19                       1
## 4             0           1  19                       1
## 5             1           0  25                       1
## 6             1           0  26                       1
##   freq_consumption_hc_food1 veg_freq num_meals food_between_meals_frequently
## 1                         1 3.000000  3.000000                             0
## 2                         1 2.103335  2.977909                             0
## 3                         1 3.000000  3.000000                             0
## 4                         1 3.000000  3.000000                             0
## 5                         1 3.000000  3.000000                             0
## 6                         1 3.000000  3.000000                             0
##   food_between_meals_never food_between_meals_sometimes smoke1 water_daily
## 1                        0                            1      0    2.472903
## 2                        0                            1      0    1.964435
## 3                        0                            1      0    2.865590
## 4                        0                            0      0    3.000000
## 5                        0                            1      0    2.863513
## 6                        0                            1      0    1.347559
##   caloric_beverages1 activity_freq tech_use alcohol_never alcohol_sometimes
## 1                  0      0.167086 0.486868             0                 1
## 2                  0      0.987521 0.000000             0                 1
## 3                  0      1.464674 0.655571             0                 1
## 4                  1      3.000000 0.000000             0                 1
## 5                  0      0.264831 0.673210             0                 1
## 6                  0      0.217455 0.625350             0                 1
##   transport_bike transport_motorbike transport_public_transportation
## 1              0                   0                               1
## 2              0                   0                               0
## 3              0                   0                               1
## 4              0                   0                               1
## 5              0                   0                               1
## 6              0                   0                               1
##   transport_walking obesity_leveloverweight eating_habit_binary
## 1                 0                       1            2.666667
## 2                 0                       1            2.360415
## 3                 0                       1            2.666667
## 4                 0                       1            2.666667
## 5                 0                       1            2.666667
## 6                 0                       1            2.666667
##   physical_activity_binary age_group_young_adult age_group_adult
## 1                -0.319782                     1               0
## 2                 0.987521                     1               0
## 3                 0.809103                     1               0
## 4                 3.000000                     1               0
## 5                -0.408379                     1               0
## 6                -0.407895                     1               0
##   age_group_senior
## 1                0
## 2                0
## 3                0
## 4                0
## 5                0
## 6                0</code></pre>
</div>
<div id="model-dt" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Model DT<a href="decision-tree-dt.html#model-dt" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="simple-dt" class="section level3 hasAnchor" number="6.3.1">
<h3><span class="header-section-number">6.3.1</span> Simple DT<a href="decision-tree-dt.html#simple-dt" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>First, let’s construct a DT model without considering the misclassification error cost.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="decision-tree-dt.html#cb120-1" tabindex="-1"></a><span class="co"># Build a model</span></span>
<span id="cb120-2"><a href="decision-tree-dt.html#cb120-2" tabindex="-1"></a>model_dt <span class="ot">&lt;-</span> <span class="fu">C5.0</span>(</span>
<span id="cb120-3"><a href="decision-tree-dt.html#cb120-3" tabindex="-1"></a>  <span class="fu">as.factor</span>(obesity_leveloverweight) <span class="sc">~</span> .,</span>
<span id="cb120-4"><a href="decision-tree-dt.html#cb120-4" tabindex="-1"></a>  <span class="at">data =</span> train_dt</span>
<span id="cb120-5"><a href="decision-tree-dt.html#cb120-5" tabindex="-1"></a>  )</span></code></pre></div>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="decision-tree-dt.html#cb121-1" tabindex="-1"></a><span class="co"># Display summary</span></span>
<span id="cb121-2"><a href="decision-tree-dt.html#cb121-2" tabindex="-1"></a><span class="fu">summary</span>(model_dt)</span></code></pre></div>
<pre><code>## 
## Call:
## C5.0.formula(formula = as.factor(obesity_leveloverweight) ~ ., data = train_dt)
## 
## 
## C5.0 [Release 2.07 GPL Edition]      Wed Apr 17 20:31:24 2024
## -------------------------------
## 
## Class specified by attribute `outcome&#39;
## 
## Read 10379 cases (27 attributes) from undefined.data
## 
## Decision tree:
## 
## fam_history_overweight1 &lt;= 0:
## :...age_group_adult &gt; 0: 1 (33/2)
## :   age_group_adult &lt;= 0:
## :   :...food_between_meals_never &gt; 0:
## :       :...alcohol_never &lt;= 0: 1 (68/8)
## :       :   alcohol_never &gt; 0: 0 (9/2)
## :       food_between_meals_never &lt;= 0:
## :       :...age &gt; 26:
## :           :...transport_public_transportation &lt;= 0: 1 (61/12)
## :           :   transport_public_transportation &gt; 0: 0 (13/5)
## :           age &lt;= 26:
## :           :...water_daily &gt; 2.987718:
## :               :...eating_habit_binary &lt;= 1.832259: 1 (14/1)
## :               :   eating_habit_binary &gt; 1.832259:
## :               :   :...gender_female &lt;= 0: 1 (77/27)
## :               :       gender_female &gt; 0: 0 (32/9)
## :               water_daily &lt;= 2.987718:
## :               :...food_between_meals_sometimes &lt;= 0: 0 (626/39)
## :                   food_between_meals_sometimes &gt; 0:
## :                   :...num_meals &lt;= 2.986637:
## :                       :...veg_freq &gt; 2.549782: 0 (73/15)
## :                       :   veg_freq &lt;= 2.549782:
## :                       :   :...caloric_beverages1 &gt; 0: 1 (11/1)
## :                       :       caloric_beverages1 &lt;= 0:
## :                       :       :...activity_freq &gt; 0.010183: 1 (67/26)
## :                       :           activity_freq &lt;= 0.010183:
## :                       :           :...tech_use &lt;= 1.58483: 0 (25/4)
## :                       :               tech_use &gt; 1.58483: 1 (3)
## :                       num_meals &gt; 2.986637:
## :                       :...transport_public_transportation &gt; 0: 0 (694/118)
## :                           transport_public_transportation &lt;= 0:
## :                           :...freq_consumption_hc_food1 &lt;= 0: 0 (14/1)
## :                               freq_consumption_hc_food1 &gt; 0:
## :                               :...water_daily &lt;= 1.49681: 0 (18/3)
## :                                   water_daily &gt; 1.49681:
## :                                   :...veg_freq &lt;= 2.104772: 1 (27/7)
## :                                       veg_freq &gt; 2.104772: 0 (27/7)
## fam_history_overweight1 &gt; 0:
## :...food_between_meals_frequently &gt; 0:
##     :...age &gt; 32: 1 (26/1)
##     :   age &lt;= 32:
##     :   :...alcohol_never &gt; 0: 0 (270/34)
##     :       alcohol_never &lt;= 0:
##     :       :...alcohol_sometimes &lt;= 0: 1 (49/8)
##     :           alcohol_sometimes &gt; 0:
##     :           :...gender_female &gt; 0: 0 (132/29)
##     :               gender_female &lt;= 0:
##     :               :...veg_freq &lt;= 2.291846: 0 (115/40)
##     :                   veg_freq &gt; 2.291846: 1 (56/24)
##     food_between_meals_frequently &lt;= 0:
##     :...num_meals &gt; 3.259033:
##         :...age &lt;= 18: 0 (92/11)
##         :   age &gt; 18:
##         :   :...num_meals &lt;= 3.998766: 1 (80/14)
##         :       num_meals &gt; 3.998766: 0 (33/4)
##         num_meals &lt;= 3.259033:
##         :...food_between_meals_sometimes &lt;= 0:
##             :...water_daily &gt; 2.01897: 1 (51/7)
##             :   water_daily &lt;= 2.01897:
##             :   :...eating_habit_binary &lt;= 1.846881: 1 (28/6)
##             :       eating_habit_binary &gt; 1.846881:
##             :       :...transport_public_transportation &lt;= 0: 1 (23/9)
##             :           transport_public_transportation &gt; 0: 0 (98/28)
##             food_between_meals_sometimes &gt; 0:
##             :...age &gt; 23: 1 (3860/63)
##                 age &lt;= 23:
##                 :...transport_public_transportation &lt;= 0:
##                     :...water_daily &gt; 2.987718: 1 (48/10)
##                     :   water_daily &lt;= 2.987718:
##                     :   :...freq_consumption_hc_food1 &lt;= 0: 1 (19/8)
##                     :       freq_consumption_hc_food1 &gt; 0:
##                     :       :...age &lt;= 20: 0 (100/24)
##                     :           age &gt; 20:
##                     :           :...caloric_beverages1 &gt; 0: 1 (4)
##                     :               caloric_beverages1 &lt;= 0:
##                     :               :...tech_use &lt;= 1.229474: 0 (46/17)
##                     :                   tech_use &gt; 1.229474: 1 (7)
##                     transport_public_transportation &gt; 0:
##                     :...water_daily &gt; 2.045561: 1 (1271/60)
##                         water_daily &lt;= 2.045561:
##                         :...num_meals &lt;= 2.997414: 1 (715/48)
##                             num_meals &gt; 2.997414:
##                             :...age &lt;= 19:
##                                 :...eating_habit_binary &lt;= 2.616983: 1 (369/169)
##                                 :   eating_habit_binary &gt; 2.616983: 0 (119/32)
##                                 age &gt; 19:
##                                 :...water_daily &lt;= 1.999278:
##                                     :...water_daily &gt; 1: 1 (290/4)
##                                     :   water_daily &lt;= 1:
##                                     :   :...activity_freq &gt; 1.958694: 0 (19/4)
##                                     :       activity_freq &lt;= 1.958694: [S1]
##                                     water_daily &gt; 1.999278:
##                                     :...veg_freq &gt; 2.997951:
##                                         :...gender_female &gt; 0: 0 (51/8)
##                                         :   gender_female &lt;= 0:
##                                         :   :...alcohol_never &lt;= 0: 1 (35/14)
##                                         :       alcohol_never &gt; 0: 0 (8/2)
##                                         veg_freq &lt;= 2.997951:
##                                         :...freq_consumption_hc_food1 &lt;= 0:
##                                             :...tech_use &gt; 1.140348: 1 (6)
##                                             :   tech_use &lt;= 1.140348:
##                                             :   :...activity_freq &lt;= 0.497373: 0 (9)
##                                             :       activity_freq &gt; 0.497373: 1 (32/14)
##                                             freq_consumption_hc_food1 &gt; 0:
##                                             :...gender_female &lt;= 0: 1 (257/49)
##                                                 gender_female &gt; 0: [S2]
## 
## SubTree [S1]
## 
## physical_activity_binary &lt;= -1.50301: 0 (9/3)
## physical_activity_binary &gt; -1.50301: 1 (73/24)
## 
## SubTree [S2]
## 
## eating_habit_binary &gt; 2.344948: 1 (9)
## eating_habit_binary &lt;= 2.344948:
## :...veg_freq &lt;= 1.99953: 1 (11/1)
##     veg_freq &gt; 1.99953:
##     :...alcohol_sometimes &lt;= 0: 1 (34/11)
##         alcohol_sometimes &gt; 0:
##         :...activity_freq &lt;= 1.28775: 0 (26/7)
##             activity_freq &gt; 1.28775: 1 (7/2)
## 
## 
## Evaluation on training data (10379 cases):
## 
##      Decision Tree   
##    ----------------  
##    Size      Errors  
## 
##      59 1076(10.4%)   &lt;&lt;
## 
## 
##     (a)   (b)    &lt;-classified as
##    ----  ----
##    2212   630    (a): class 0
##     446  7091    (b): class 1
## 
## 
##  Attribute usage:
## 
##  100.00% fam_history_overweight1
##   97.01% age
##   88.82% food_between_meals_sometimes
##   84.77% num_meals
##   81.77% food_between_meals_frequently
##   52.82% water_daily
##   43.83% transport_public_transportation
##   18.23% age_group_adult
##   17.91% food_between_meals_never
##    8.57% veg_freq
##    8.19% gender_female
##    8.16% eating_habit_binary
##    7.15% alcohol_never
##    6.29% freq_consumption_hc_food1
##    4.04% alcohol_sometimes
##    2.60% activity_freq
##    1.57% caloric_beverages1
##    1.23% tech_use
##    0.79% physical_activity_binary
## 
## 
## Time: 0.1 secs</code></pre>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="decision-tree-dt.html#cb123-1" tabindex="-1"></a><span class="fu">plot</span>(model_dt)</span></code></pre></div>
<p><img src="_main_files/figure-html/model_dt_summary_05-1.png" width="672" /></p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="decision-tree-dt.html#cb124-1" tabindex="-1"></a><span class="fu">varImp</span>(model_dt)</span></code></pre></div>
<pre><code>##                                 Overall
## fam_history_overweight1          100.00
## age                               97.01
## food_between_meals_sometimes      88.82
## num_meals                         84.77
## food_between_meals_frequently     81.77
## water_daily                       52.82
## transport_public_transportation   43.83
## age_group_adult                   18.23
## food_between_meals_never          17.91
## veg_freq                           8.57
## gender_female                      8.19
## eating_habit_binary                8.16
## alcohol_never                      7.15
## freq_consumption_hc_food1          6.29
## alcohol_sometimes                  4.04
## activity_freq                      2.60
## caloric_beverages1                 1.57
## tech_use                           1.23
## physical_activity_binary           0.79
## gender_male                        0.00
## smoke1                             0.00
## transport_bike                     0.00
## transport_motorbike                0.00
## transport_walking                  0.00
## age_group_young_adult              0.00
## age_group_senior                   0.00</code></pre>
<p>According to the variable importance chart, <code>fam_history_overweight</code> is identified as one of the most significant features for making decisions. This makes intuitive sense since family who are overweight tend to have children who are also overweight. <code>Age</code>, on the other hand, exhibits an intriguing aspect as it ranks second in importance. We suspect that older individuals may be more prone to obesity due to slower metabolism.</p>
</div>
<div id="dt-with-cost-matrix" class="section level3 hasAnchor" number="6.3.2">
<h3><span class="header-section-number">6.3.2</span> DT with Cost Matrix<a href="decision-tree-dt.html#dt-with-cost-matrix" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now, we will introduce a cost matrix where misclassifying an individual as not obese when they are actually obese incurs significant business costs. Conversely, incorrectly labeling someone as obese but discovering they are healthy carries less financial consequence.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="decision-tree-dt.html#cb126-1" tabindex="-1"></a><span class="co"># Build cost matrix</span></span>
<span id="cb126-2"><a href="decision-tree-dt.html#cb126-2" tabindex="-1"></a>cost_matrix_dt <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>,</span>
<span id="cb126-3"><a href="decision-tree-dt.html#cb126-3" tabindex="-1"></a>                         <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="at">Actual =</span> <span class="fu">c</span>(<span class="st">&#39;0&#39;</span>, <span class="st">&#39;1&#39;</span>),</span>
<span id="cb126-4"><a href="decision-tree-dt.html#cb126-4" tabindex="-1"></a>                                         <span class="at">Predicted =</span> <span class="fu">c</span>(<span class="st">&#39;0&#39;</span>, <span class="st">&#39;1&#39;</span>)))</span>
<span id="cb126-5"><a href="decision-tree-dt.html#cb126-5" tabindex="-1"></a></span>
<span id="cb126-6"><a href="decision-tree-dt.html#cb126-6" tabindex="-1"></a><span class="co"># Build a model</span></span>
<span id="cb126-7"><a href="decision-tree-dt.html#cb126-7" tabindex="-1"></a>model_dt_cost <span class="ot">&lt;-</span> <span class="fu">C5.0</span>(</span>
<span id="cb126-8"><a href="decision-tree-dt.html#cb126-8" tabindex="-1"></a>  <span class="fu">as.factor</span>(obesity_leveloverweight) <span class="sc">~</span> .,</span>
<span id="cb126-9"><a href="decision-tree-dt.html#cb126-9" tabindex="-1"></a>  <span class="at">data =</span> train_dt,</span>
<span id="cb126-10"><a href="decision-tree-dt.html#cb126-10" tabindex="-1"></a>  <span class="at">costs =</span> cost_matrix_dt</span>
<span id="cb126-11"><a href="decision-tree-dt.html#cb126-11" tabindex="-1"></a>  )</span></code></pre></div>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="decision-tree-dt.html#cb127-1" tabindex="-1"></a><span class="co"># Display summary</span></span>
<span id="cb127-2"><a href="decision-tree-dt.html#cb127-2" tabindex="-1"></a><span class="fu">summary</span>(model_dt_cost)</span></code></pre></div>
<pre><code>## 
## Call:
## C5.0.formula(formula = as.factor(obesity_leveloverweight) ~ ., data =
##  train_dt, costs = cost_matrix_dt)
## 
## 
## C5.0 [Release 2.07 GPL Edition]      Wed Apr 17 20:31:26 2024
## -------------------------------
## 
## Class specified by attribute `outcome&#39;
## 
## Read 10379 cases (27 attributes) from undefined.data
## Read misclassification costs from undefined.costs
## 
## Decision tree:
## 
## food_between_meals_frequently &gt; 0:
## :...age_group_adult &gt; 0: 1 (22/1)
## :   age_group_adult &lt;= 0:
## :   :...gender_female &lt;= 0:
## :       :...alcohol_never &lt;= 0: 1 (326/186)
## :       :   alcohol_never &gt; 0:
## :       :   :...water_daily &gt; 2.976229: 1 (20/9)
## :       :       water_daily &lt;= 2.976229:
## :       :       :...fam_history_overweight1 &lt;= 0: 0 (36/1)
## :       :           fam_history_overweight1 &gt; 0: 1 (99/80)
## :       gender_female &gt; 0:
## :       :...fam_history_overweight1 &lt;= 0:
## :           :...veg_freq &lt;= 2.278644:
## :           :   :...age &lt;= 20: 0 (95/3)
## :           :   :   age &gt; 20: 1 (33/24)
## :           :   veg_freq &gt; 2.278644:
## :           :   :...transport_public_transportation &lt;= 0: 1 (10/8)
## :           :       transport_public_transportation &gt; 0: 0 (312/4)
## :           fam_history_overweight1 &gt; 0:
## :           :...alcohol_never &gt; 0: 0 (162/13)
## :               alcohol_never &lt;= 0:
## :               :...num_meals &lt;= 3.058539: 1 (118/82)
## :                   num_meals &gt; 3.058539: 0 (25)
## food_between_meals_frequently &lt;= 0:
## :...fam_history_overweight1 &gt; 0:
##     :...num_meals &lt;= 3.998766: 1 (7752/906)
##     :   num_meals &gt; 3.998766:
##     :   :...alcohol_never &lt;= 0: 1 (34/26)
##     :       alcohol_never &gt; 0: 0 (53/2)
##     fam_history_overweight1 &lt;= 0:
##     :...food_between_meals_never &gt; 0: 1 (78/15)
##         food_between_meals_never &lt;= 0:
##         :...transport_public_transportation &lt;= 0:
##             :...food_between_meals_sometimes &lt;= 0: 0 (19/1)
##             :   food_between_meals_sometimes &gt; 0: 1 (194/78)
##             transport_public_transportation &gt; 0:
##             :...water_daily &gt; 2.975528:
##                 :...gender_female &lt;= 0: 1 (58/17)
##                 :   gender_female &gt; 0:
##                 :   :...veg_freq &lt;= 2.499626: 1 (17/9)
##                 :       veg_freq &gt; 2.499626: 0 (8)
##                 water_daily &lt;= 2.975528:
##                 :...num_meals &lt;= 2.986637: 1 (171/100)
##                     num_meals &gt; 2.986637:
##                     :...age &lt;= 18: 0 (321/33)
##                         age &gt; 18:
##                         :...gender_female &lt;= 0:
##                             :...food_between_meals_sometimes &lt;= 0: 0 (15/1)
##                             :   food_between_meals_sometimes &gt; 0: 1 (151/103)
##                             gender_female &gt; 0:
##                             :...num_meals &lt;= 3.105007: 1 (203/165)
##                                 num_meals &gt; 3.105007: 0 (47/2)
## 
## 
## Evaluation on training data (10379 cases):
## 
##         Decision Tree       
##    -----------------------  
##    Size      Errors   Cost  
## 
##      27 1869(18.0%)   0.20   &lt;&lt;
## 
## 
##     (a)   (b)    &lt;-classified as
##    ----  ----
##    1033  1809    (a): class 0
##      60  7477    (b): class 1
## 
## 
##  Attribute usage:
## 
##  100.00% food_between_meals_frequently
##   96.45% fam_history_overweight1
##   85.65% num_meals
##   16.72% gender_female
##   14.70% transport_public_transportation
##   12.35% food_between_meals_never
##   12.12% age_group_adult
##   11.04% water_daily
##    8.41% alcohol_never
##    8.33% age
##    4.58% veg_freq
##    3.65% food_between_meals_sometimes
## 
## 
## Time: 0.0 secs</code></pre>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="decision-tree-dt.html#cb129-1" tabindex="-1"></a><span class="fu">plot</span>(model_dt_cost)</span></code></pre></div>
<p><img src="_main_files/figure-html/model_dt_cost_summary_05-1.png" width="672" /></p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="decision-tree-dt.html#cb130-1" tabindex="-1"></a><span class="fu">varImp</span>(model_dt_cost)</span></code></pre></div>
<pre><code>##                                 Overall
## food_between_meals_frequently    100.00
## fam_history_overweight1           96.45
## num_meals                         85.65
## gender_female                     16.72
## transport_public_transportation   14.70
## food_between_meals_never          12.35
## age_group_adult                   12.12
## water_daily                       11.04
## alcohol_never                      8.41
## age                                8.33
## veg_freq                           4.58
## food_between_meals_sometimes       3.65
## gender_male                        0.00
## freq_consumption_hc_food1          0.00
## smoke1                             0.00
## caloric_beverages1                 0.00
## activity_freq                      0.00
## tech_use                           0.00
## alcohol_sometimes                  0.00
## transport_bike                     0.00
## transport_motorbike                0.00
## transport_walking                  0.00
## eating_habit_binary                0.00
## physical_activity_binary           0.00
## age_group_young_adult              0.00
## age_group_senior                   0.00</code></pre>
<p>With a cost matrix implemented, the variable importance chart now places a greater significance on <code>food_between_meals_frequently</code> as a top feature, along with <code>fam_history_overweight</code> and <code>num_meals</code>. These features, two of which are behavioral indicators, highlight the potential for someone overconsuming food that may contribute to becoming obese.</p>
</div>
</div>
<div id="evaluate-dt" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Evaluate DT<a href="decision-tree-dt.html#evaluate-dt" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="simple-dt-1" class="section level3 hasAnchor" number="6.4.1">
<h3><span class="header-section-number">6.4.1</span> Simple DT<a href="decision-tree-dt.html#simple-dt-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="decision-tree-dt.html#cb132-1" tabindex="-1"></a><span class="co"># Make a prediction</span></span>
<span id="cb132-2"><a href="decision-tree-dt.html#cb132-2" tabindex="-1"></a>prediction_dt <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_dt, test_dt)</span>
<span id="cb132-3"><a href="decision-tree-dt.html#cb132-3" tabindex="-1"></a>prediction_dt_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_dt, test_dt, <span class="at">type=</span><span class="st">&quot;prob&quot;</span>)</span>
<span id="cb132-4"><a href="decision-tree-dt.html#cb132-4" tabindex="-1"></a><span class="fu">summary</span>(prediction_dt)</span></code></pre></div>
<pre><code>##    0    1 
## 2590 7789</code></pre>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="decision-tree-dt.html#cb134-1" tabindex="-1"></a><span class="co"># Perform confusion matrix</span></span>
<span id="cb134-2"><a href="decision-tree-dt.html#cb134-2" tabindex="-1"></a>cm_dt <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(</span>
<span id="cb134-3"><a href="decision-tree-dt.html#cb134-3" tabindex="-1"></a>  <span class="fu">as.factor</span>(prediction_dt),</span>
<span id="cb134-4"><a href="decision-tree-dt.html#cb134-4" tabindex="-1"></a>  <span class="fu">as.factor</span>(test_dt<span class="sc">$</span>obesity_leveloverweight),</span>
<span id="cb134-5"><a href="decision-tree-dt.html#cb134-5" tabindex="-1"></a>  <span class="at">positive =</span> <span class="st">&#39;1&#39;</span></span>
<span id="cb134-6"><a href="decision-tree-dt.html#cb134-6" tabindex="-1"></a>  )</span>
<span id="cb134-7"><a href="decision-tree-dt.html#cb134-7" tabindex="-1"></a>cm_dt</span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    0    1
##          0 1993  597
##          1  770 7019
##                                           
##                Accuracy : 0.8683          
##                  95% CI : (0.8616, 0.8747)
##     No Information Rate : 0.7338          
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
##                                           
##                   Kappa : 0.656           
##                                           
##  Mcnemar&#39;s Test P-Value : 3.287e-06       
##                                           
##             Sensitivity : 0.9216          
##             Specificity : 0.7213          
##          Pos Pred Value : 0.9011          
##          Neg Pred Value : 0.7695          
##              Prevalence : 0.7338          
##          Detection Rate : 0.6763          
##    Detection Prevalence : 0.7505          
##       Balanced Accuracy : 0.8215          
##                                           
##        &#39;Positive&#39; Class : 1               
## </code></pre>
<p>Based on the confusion matrix, we observe that the model achieves an accuracy of <code>0.8683</code>, sensitivity of <code>0.9216</code>, and a Kappa coefficient of <code>0.656</code>. We will assess these results towards the conclusion of the assignment when we have completed stacked models.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="decision-tree-dt.html#cb136-1" tabindex="-1"></a><span class="co"># Plot AUC</span></span>
<span id="cb136-2"><a href="decision-tree-dt.html#cb136-2" tabindex="-1"></a>pred <span class="ot">&lt;-</span> ROCR<span class="sc">::</span><span class="fu">prediction</span>(</span>
<span id="cb136-3"><a href="decision-tree-dt.html#cb136-3" tabindex="-1"></a>  prediction_dt_prob[,<span class="dv">2</span>],</span>
<span id="cb136-4"><a href="decision-tree-dt.html#cb136-4" tabindex="-1"></a>  test_dt<span class="sc">$</span>obesity_leveloverweight</span>
<span id="cb136-5"><a href="decision-tree-dt.html#cb136-5" tabindex="-1"></a>  )</span>
<span id="cb136-6"><a href="decision-tree-dt.html#cb136-6" tabindex="-1"></a>perf <span class="ot">&lt;-</span> ROCR<span class="sc">::</span><span class="fu">performance</span>(pred, <span class="at">measure =</span> <span class="st">&quot;tpr&quot;</span>, <span class="at">x.measure =</span> <span class="st">&quot;fpr&quot;</span>)</span>
<span id="cb136-7"><a href="decision-tree-dt.html#cb136-7" tabindex="-1"></a>auc <span class="ot">&lt;-</span> ROCR<span class="sc">::</span><span class="fu">performance</span>(pred, <span class="at">measure=</span><span class="st">&quot;auc&quot;</span>)</span>
<span id="cb136-8"><a href="decision-tree-dt.html#cb136-8" tabindex="-1"></a></span>
<span id="cb136-9"><a href="decision-tree-dt.html#cb136-9" tabindex="-1"></a>auc <span class="ot">&lt;-</span> <span class="fu">round</span>(auc<span class="sc">@</span>y.values[[<span class="dv">1</span>]],<span class="dv">3</span>)</span>
<span id="cb136-10"><a href="decision-tree-dt.html#cb136-10" tabindex="-1"></a>roc.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">fpr=</span><span class="fu">unlist</span>(perf<span class="sc">@</span>x.values),</span>
<span id="cb136-11"><a href="decision-tree-dt.html#cb136-11" tabindex="-1"></a>                       <span class="at">tpr=</span><span class="fu">unlist</span>(perf<span class="sc">@</span>y.values),</span>
<span id="cb136-12"><a href="decision-tree-dt.html#cb136-12" tabindex="-1"></a>                       <span class="at">model=</span><span class="st">&quot;GLM&quot;</span>)</span>
<span id="cb136-13"><a href="decision-tree-dt.html#cb136-13" tabindex="-1"></a></span>
<span id="cb136-14"><a href="decision-tree-dt.html#cb136-14" tabindex="-1"></a><span class="fu">ggplot</span>(roc.data, <span class="fu">aes</span>(<span class="at">x=</span>fpr, <span class="at">ymin=</span><span class="dv">0</span>, <span class="at">ymax=</span>tpr)) <span class="sc">+</span></span>
<span id="cb136-15"><a href="decision-tree-dt.html#cb136-15" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb136-16"><a href="decision-tree-dt.html#cb136-16" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>tpr), <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb136-17"><a href="decision-tree-dt.html#cb136-17" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb136-18"><a href="decision-tree-dt.html#cb136-18" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">&quot;Simple Decision Tree ROC Curve w/ AUC=&quot;</span>, auc)) <span class="sc">+</span></span>
<span id="cb136-19"><a href="decision-tree-dt.html#cb136-19" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/plot_auc_dt_05-1.png" width="672" /></p>
</div>
<div id="dt-with-cost-matrix-1" class="section level3 hasAnchor" number="6.4.2">
<h3><span class="header-section-number">6.4.2</span> DT with Cost Matrix<a href="decision-tree-dt.html#dt-with-cost-matrix-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="decision-tree-dt.html#cb137-1" tabindex="-1"></a><span class="co"># Make a prediction</span></span>
<span id="cb137-2"><a href="decision-tree-dt.html#cb137-2" tabindex="-1"></a>prediction_dt_cost <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_dt_cost, test_dt)</span>
<span id="cb137-3"><a href="decision-tree-dt.html#cb137-3" tabindex="-1"></a></span>
<span id="cb137-4"><a href="decision-tree-dt.html#cb137-4" tabindex="-1"></a></span>
<span id="cb137-5"><a href="decision-tree-dt.html#cb137-5" tabindex="-1"></a><span class="co"># Perform confusion matrix</span></span>
<span id="cb137-6"><a href="decision-tree-dt.html#cb137-6" tabindex="-1"></a>cm_dt_cost <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(</span>
<span id="cb137-7"><a href="decision-tree-dt.html#cb137-7" tabindex="-1"></a>  <span class="fu">as.factor</span>(prediction_dt_cost),</span>
<span id="cb137-8"><a href="decision-tree-dt.html#cb137-8" tabindex="-1"></a>  <span class="fu">as.factor</span>(test_dt<span class="sc">$</span>obesity_leveloverweight),</span>
<span id="cb137-9"><a href="decision-tree-dt.html#cb137-9" tabindex="-1"></a>  <span class="at">positive =</span> <span class="st">&#39;1&#39;</span></span>
<span id="cb137-10"><a href="decision-tree-dt.html#cb137-10" tabindex="-1"></a>  )</span>
<span id="cb137-11"><a href="decision-tree-dt.html#cb137-11" tabindex="-1"></a>cm_dt_cost</span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    0    1
##          0  880   90
##          1 1883 7526
##                                           
##                Accuracy : 0.8099          
##                  95% CI : (0.8022, 0.8174)
##     No Information Rate : 0.7338          
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
##                                           
##                   Kappa : 0.3866          
##                                           
##  Mcnemar&#39;s Test P-Value : &lt; 2.2e-16       
##                                           
##             Sensitivity : 0.9882          
##             Specificity : 0.3185          
##          Pos Pred Value : 0.7999          
##          Neg Pred Value : 0.9072          
##              Prevalence : 0.7338          
##          Detection Rate : 0.7251          
##    Detection Prevalence : 0.9065          
##       Balanced Accuracy : 0.6533          
##                                           
##        &#39;Positive&#39; Class : 1               
## </code></pre>
<p>Based on the confusion matrix, we observe that the model achieves an accuracy of <code>0.8099</code>, sensitivity of <code>0.9882</code>, and a Kappa coefficient of <code>0.3866</code>. We will assess these results towards the conclusion of the assignment when we have completed stacked models.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="k-neareast-neighbor-knn.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="support-vector-machine-svm.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
